version: "3"
services:
  postal:
    image: ${POSTAL_IMAGE}
    depends_on:
      - mariadb
      - rabbitmq
      - rspamd
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - "./docker/ci-config:/config"
      - "./mail:/mail"
    environment:
      POSTAL_CONFIG_ROOT: /config
      POSTAL_ENV: test
      KATAPULT_CONFIG_FILE: /ci-config.yml
      WAIT_FOR_TIMEOUT: 90
      WAIT_FOR_TARGETS: |-
        mariadb:3306
        rabbitmq:5672
        rspamd:11334

  dovecot:
    build:
      context: ./docker/dovecot
      dockerfile: Dockerfile
    restart: always
    ports:
      - "143:143"   # IMAP
      - "993:993"   # IMAPS
      - "110:110"   # POP3
      - "995:995"   # POP3S
    volumes:
      - "./mail:/mail"
      - "./docker/dovecot/users:/etc/dovecot/users"
    depends_on:
      - postal
    environment:
      - DOVECOT_CONFIG_DIR=/etc/dovecot

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ALLOW_EMPTY_PASSWORD: 'yes'
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

  rabbitmq:
    image: rabbitmq:3
    restart: always

  rspamd:
    image: rspamd/rspamd
    restart: always
    ports:
      - "11333:11333"
      - "11334:11334"
      - "11335:11335"
    environment:
      RSPAMD_PASSWORD: "password"
    volumes:
      - ./docker/rspamd:/etc/rspamd
