# Group modules
group {
    id = "antivirus";
    enabled = true;
    strictness = high;
}
group {
    id = "spf";
    enabled = true;
    strictness = high;
}
group {
    id = "dmarc";
    enabled = true;
    strictness = high;
}
group {
    id = "bayes";
    enabled = true;
    strictness = high;
}
group {
    id = "reputation";
    enabled = true;
    strictness = high;
}
