# Mailbox locations and namespaces
mail_location = maildir:/mail/v1/%d/%n

# Mailbox namespaces
namespace inbox {
  inbox = yes
  location = 
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Trash {
    special_use = \Trash
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox "Sent Messages" {
    special_use = \Sent
  }
}

# Mailbox settings
mailbox_list_index = yes
mailbox_list_index_very_dirty_syncs = yes
mailbox_list_index_dirty_timeout = 1h

# Maildir specific settings
maildir_copy_with_hardlinks = yes
maildir_very_dirty_syncs = yes
maildir_broken_filename_sizes = yes 