# Local Delivery Agent configuration
protocol lda {
  postmaster_address = postmaster@%d
  mail_plugins = $mail_plugins sieve
  quota_full_tempfail = yes
  deliver_log_format = msgid=%m: %$
  rejection_reason = Your message to <%t> was automatically rejected:%n%r
} 