# IMAP protocol configuration
protocol imap {
  mail_plugins = $mail_plugins imap_quota
  imap_max_line_length = 64k
  imap_idle_notify_interval = 2 mins
  imap_id_send = name * version
  imap_id_log = name * version
  imap_capability = +IMAP4rev1 +LITERAL+ +SASL-IR +LOGIN-REFERRALS +ID +ENABLE +STARTTLS +AUTH=PLAIN +AUTH=LOGIN
} 