# POP3 protocol configuration
protocol pop3 {
  mail_plugins = $mail_plugins
  pop3_uidl_format = %08Xu%08Xv
  pop3_client_workarounds = outlook-no-nuls oe-ns-eoh
  pop3_deleted_flag = deleted
  pop3_reuse_xuidl = yes
  pop3_save_uidl = yes
  pop3_logout_format = top=%t/%p, retr=%r/%b, del=%d/%m, size=%s
} 