# Sieve configuration
plugin {
  sieve = ~/.dovecot.sieve
  sieve_global_path = /var/lib/dovecot/sieve/default.sieve
  sieve_dir = ~/sieve
  sieve_global_dir = /var/lib/dovecot/sieve/
  sieve_extensions = +notify +imapflags +editheader
  sieve_max_actions = 32
  sieve_max_redirects = 4
  sieve_quota_max_storage = 100M
  sieve_quota_max_scripts = 50
} 