# Bayesian classifier configuration
classifier {
    tokenizer {
        name = "osb";
    }

    name = "bayes";
    backend = "sqlite3";
    database = "/var/lib/rspamd/bayes.db";
    autolearn = true;
    min_tokens = 11;
}
