# Local Postal configuration overrides
smtp:
  host: pxa.mail.venmail.io
  port: 587
  username: # Complete when Postal is running and you can
  password: # generate the credentials within the interface.
  from_name: Postal
  from_address: postal@yourdomain.com
  ssl: false
  tls: true
  enable_starttls_auto: true
